version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fruveg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
